### ISSUE TITLE
Citations should be marked

### ISSUE THREAD

**Issue by NelDav** [tfachmann/MdCollab#10]
Edit the css file. Because citations should be marked in anyway

Ideas:
* A Frame
* Backgroundcolor

**Comment by tfachmann** [comment]
This will be solved, when we use a github-flavoured markdown css file such as [this](https://gist.github.com/forivall/7d5a304a8c3c809f0ba96884a7cf9d7e) I have used for a different project.

**Comment by NelDav** [comment]
I think it would be a good idea to let the user select a css file. That would offer much more adaptability for the user.
It would be nice if there are multiple predefined css files and also the possibility to specify your own css file.

**Comment by tfachmann** [comment]
Yes, I agree.

Regarding this I suggest you separate the CSS files in #14 so that we have

1. one (or multiple css) file(s) to handle the style of the output. A use defined style could be applied here aswell.
2. one file regarding our page (body, textarea, ...)

We would have to ensure, the file in (2) overrides (1) as (1) might already make definitions regarding body or textareas.

**Comment by NelDav** [comment]
Yes you are right. I will have a look on that.
